version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-zli
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
